name: "\U0001F41E Bug report"
description: File a bug to help us improve Infinity Film Studio.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the problem.
      placeholder: Script chat fails when session_id is null.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include the exact requests or UI clicks you performed.
      placeholder: |
        1. Start backend with `python Launcher.py --ui web`
        2. Go to /script chat
        3. Send "Hello"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: The assistant responds with a greeting and a new session_id.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Response 500 with stack trace...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Git SHA or release tag.
  - type: dropdown
    id: clients
    attributes:
      label: Client surface
      multiple: true
      options:
        - Web
        - CLI
        - Desktop (Tkinter)
        - API only
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or drop screenshots.
